"""Shared planning utilities — XML validation, sanitization, and plan I/O.

Both PlannerAgent and ReplannerAgent use these helpers so the logic lives in
one place rather than being duplicated across agents.
"""

import logging
import re
import xml.etree.ElementTree as ET
from pathlib import Path

from sago.core.parser import MarkdownParser
from sago.models.plan import Plan
from sago.utils.tracer import tracer
from sago.validation import PlanValidator, ValidationResult

logger = logging.getLogger(__name__)


def sanitize_xml(xml_str: str) -> str:
    """Fix bare ``&`` in text content (common LLM output issue)."""
    return re.sub(r"&(?!amp;|lt;|gt;|quot;|apos;|#)", "&amp;", xml_str)


def validate_xml_structure(plan_xml: str) -> None:
    """Check for required tags and well-formed XML.

    Raises ``ValueError`` on any structural issue.
    """
    if "<phases>" not in plan_xml or "</phases>" not in plan_xml:
        raise ValueError("Plan missing <phases> tags")
    if "<phase" not in plan_xml:
        raise ValueError("Plan has no phases")
    if "<task" not in plan_xml:
        raise ValueError("Plan has no tasks")

    try:
        ET.fromstring(plan_xml)
    except ET.ParseError as e:
        raise ValueError(f"Invalid XML structure: {e}") from e


def validate_plan_semantics(
    plan_xml: str, parser: MarkdownParser | None = None
) -> ValidationResult:
    """Parse XML into a ``Plan`` model and run semantic validation."""
    _parser = parser or MarkdownParser()
    phases = _parser.parse_xml_tasks(plan_xml)
    plan = Plan(phases=phases)
    return PlanValidator().validate(plan)


def format_validation_errors(validation: ValidationResult) -> str:
    """Format validation errors as feedback for an LLM retry prompt."""
    lines = ["The generated plan has the following errors that must be fixed:"]
    for issue in validation.errors:
        loc = f" (task {issue.task_id})" if issue.task_id else ""
        lines.append(f"  - {issue.code}{loc}: {issue.message}")
    return "\n".join(lines)


def extract_xml_from_response(content: str) -> str:
    """Extract ``<phases>...</phases>`` from raw LLM output.

    Raises ``ValueError`` if the block is not found.
    """
    xml_start = content.find("<phases>")
    xml_end = content.find("</phases>") + len("</phases>")
    if xml_start == -1 or xml_end < len("</phases>"):
        raise ValueError("Response does not contain valid XML structure")
    return content[xml_start:xml_end]


_PLAN_MD_TEMPLATE = """\
# PLAN.md

> **CRITICAL COMPONENT:** This file uses a specific XML schema to force the AI into "Atomic Task" mode.

```xml
{xml}
```

## Task Structure Schema

The `<phases>` block contains:
- **`<dependencies>`** (optional): Lists third-party packages needed by the project. \
Each package is a `<package>` element with optional version constraints (e.g. `flask>=2.0`).
- **`<review>`** (optional): Instructions for post-phase code review. If present, a review \
runs automatically after each phase completes and feedback carries forward to the next phase.

Each `<task>` has attributes:
- **id:** Unique identifier (phase.task format)
- **depends_on:** (optional) Comma-separated task IDs this task depends on. Omit to depend \
on all prior tasks in the phase.

Each `<task>` must contain child elements:
- **name:** Clear, actionable task name
- **files:** Specific files to create/modify
- **action:** Detailed implementation instructions
- **verify:** Command to verify task completion
- **done:** Acceptance criteria

## Execution Rules

1. **Follow task dependencies** - Check `depends_on` to determine task order. \
Tasks without `depends_on` depend on all prior tasks in their phase.
2. **Parallel between phases** - Independent phases can run concurrently
3. **Verify before proceeding** - Each task must pass verification
4. **Update STATE.md** - Log progress after each task
5. **Atomic commits** - One commit per completed task

---

*{attribution}*
"""


def save_plan(plan_path: Path, plan_xml: str, agent_name: str = "sago") -> None:
    """Write PLAN.md using the standard template."""
    content = _PLAN_MD_TEMPLATE.format(xml=plan_xml, attribution=f"Generated by {agent_name}")
    plan_path.write_text(content, encoding="utf-8")
    logger.info("Plan saved to %s", plan_path)
    tracer.emit(
        "file_write",
        agent_name,
        {
            "path": str(plan_path.name),
            "size_bytes": len(content.encode("utf-8")),
            "content_preview": content[:2000],
        },
    )
